# render.yaml
services:
  - type: web
    name: elite-english
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py createsuperuser --noinput || true
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn elite_english.wsgi:application
    envVars:
      - key: DATABASE_URL
        value: postgresql://avnadmin:YOUR_PASSWORD@YOUR_HOST.aivencloud.com:YOUR_PORT/defaultdb?sslmode=require
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: whitecollar-1.onrender.com,.onrender.com
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@eliteenglish.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: admin123
